### ISSUE TITLE
Exporting detected lines

### ISSUE THREAD

**Issue by ghost** [OMMR4all/ommr4all-line-detection#8]
@Gawajn @ChWick Thank you for your hard work,
- Is the code suitable to be trained to detect text-lines? Because it seems that the code detects baselines as shown when using `--debug true`.
- Will you include an export function, perhaps exporting the detected text-lines to page-xml.

**Comment by ChWick** [comment]
- This project only aims to only detect staff lines, it is not intended to detect baselines of text
- Since no text will be detected by this module, page xml is not relevant.
